version: '3'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      TZ: Asia/Seoul
  web-jdbc:
    build:
      context: ./web-jdbc
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8081:8080"
  webflux-jdbc:
    build:
      context: ./webflux-jdbc
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8082:8080"
  webflux-r2dbc:
    build:
      context: ./webflux-r2dbc
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8083:8080"
